spring:
  application:
    name: license-server
  datasource:
    url: jdbc:mysql://platform-qa-db.cxb5wiohfeko.ap-northeast-2.rds.amazonaws.com:8204/licenses
    username: virnect-license
    password: virnect1234
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: AKIARQGLJD3UHE5MGO5U
    password: BDPEKBJR3TV38/5vwlb8ndX2jcNgj5QQLN+JdgR1JmVa
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://stgeureka.virnect.com/eureka

server:
  port: 8632

