spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/workspace?serverTimezone=UTC
    username: virnect-workspace
    password: virnect1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
    redis:
      port: 6379
      database: 0
      password: qjsprxm0!
      host: 192.168.0.121

## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "upload/"
  url: "http://localhost:${server.port}"
  allow-extension: "gif,jpg,jpeg,png"

## User Server Configuration
user:
  serverUrl: "http://192.168.6.3:8081/users"

## Message Server Configuration
message:
  serverUrl: "http://192.168.6.3:8084/messages"

serverUrl: "http://192.168.6.3:8082"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.6.3:8761/eureka

## Process Server Configuration
process:
  serverUrl: "http://192.168.6.3:8083/processes"
