spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/workspace?serverTimezone=UTC
    username: virnect-workspace
    password: virnect1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    host: 192.168.6.3
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
  messages:
    encoding: UTF-8
    basename: classpath:/messages
  zipkin:
    enabled: false
logging:
  level:
    com.virnect.workspace.application.*: INFO

## Server Configuration
server:
  port: 8082
  ssl:
    enabled: true
    key-store: virnect.pfx
    key-store-type: PKCS12
    key-store-password: 123456

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false


## Mail send rediect Url
serverUrl: "http://192.168.6.3:8082"
redirectUrl: "https://192.168.6.3:8878"
contactUrl: "http://192.168.6.3:3000/contact/inquiry"
accountUrl: "https://192.168.6.3:8822"
supportUrl: "http://192.168.6.3:3000/contact/inquiry"

## Feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: FULL

hystrix:
  command:
    "UserRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "ProcessRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "LicenseRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "MessageRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50

# monitoring
management:
  endpoints:
    enabled-by-default: false

## Minio
minio:
  access-key: "virnect"
  secret-key: "Qjsprxm13@$"
  server: "https://192.168.6.3:2838"
  bucket: "virnect-platform"
  resource: "workspace/profile"
  extension: "gif,jpg,jpeg,png"

## 워크스페이스 커스텀
workspace:
  on-premise:
    max-have-workspace-amount: 2


user-server:
  ribbon:
    listOfServers: http://192.168.6.3:8081
license-server:
  ribbon:
    listOfServers: http://192.168.6.3:8632
message-server:
  ribbon:
    listOfServers: http://192.168.6.3:8084