spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/smic?characterEncoding=UTF-8&serverTimezone=UTC
    username: virnect-smic
    password: virnect1234!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
  redis:
    port: 32768
    database: 0
    host: localhost
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.virnect.workspace.application.*: DEBUG


## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "upload/"
  url: "http://localhost:${server.port}"
  allow-extension: "gif,jpg,jpeg,png"

# User Server Configuration
user:
  serverUrl: "http://localhost:8081/users"

# Message Server Configuration
message:
  serverUrl: "http://localhost:8084/messages"

serverUrl: "http://localhost:8082"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Process Server Configuration
process:
  serverUrl: "http://localhost:8083/processes"

## AWS Storage
cloud:
  aws:
    credentials:
      access-key: AKIAIYFYOR4X6LM3YKSQ
      secret-key: 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
    region:
      auto: true
    s3:
      bucket:
        name: "virnect-admin"
        resource: "resource"
