spring:
  application:
    name: license-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/smic?serverTimezone=UTC
    username: virnect-smic
    password: virnect1234!
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.6.3:8761/eureka
