spring:
  application:
    name: license-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/licenses?serverTimezone=UTC
    username: virnect-license
    password: virnect1234
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      format_sql: true
    open-in-view: false
  mail:
    host: email-smtp.us-west-2.amazonaws.com
    port: 587
    username: AKIARQGLJD3UHE5MGO5U
    password: BDPEKBJR3TV38/5vwlb8ndX2jcNgj5QQLN+JdgR1JmVa
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.6.3:8761/eureka

server:
  port: 8632

# User Server Configuration
user:
  serverUrl: "http://192.168.6.3:8081/users"
