spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://localhost:3306/workspace?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    port: 32768
    database: 0
    host: localhost
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
  messages:
    encoding: UTF-8
    basename: classpath:/messages

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.virnect.workspace.application.*: DEBUG

## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "virnect-platform/workspace/profile"
  url: "http://192.168.6.3:${server.port}/workspaces/"
  allow-extension: "gif,jpg,jpeg,png"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


## Mail send rediect Url
serverUrl: "http://localhost:8082"
redirectUrl: "http://192.168.6.3:8878"
contactUrl: "http://192.168.6.3:3000/contact/inquiry"
accountUrl: "https://192.168.6.3:8822"
supportUrl: "http://192.168.6.3:3000/contact/inquiry"

## Feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
hystrix:
  command:
    "LicenseRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "UserRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "MessageRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50

# monitoring
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}

## AWS Storage
cloud:
  aws:
    credentials:
      access-key: virnect
      secret-key: virnect0!
    region:
      auto: true
    s3:
      bucket:
        name: "virnect-platform"
        resource: "workspace/profile"

## Minio
minio:
  url : "http://192.168.6.3:2838"