spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/workspace?serverTimezone=UTC
    username: virnect-workspace
    password: virnect1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    host: 192.168.6.3
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
  messages:
    encoding: UTF-8
    basename: classpath:/messages

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.virnect.workspace.application.*: DEBUG

## Server Configuration
server:
  port: 8082
#  address: 192.168.6.3

## Project Configuration
file:
  upload-path: "upload/"
  url: "http://192.168.6.3:${server.port}/workspaces/"
  allow-extension: "gif,jpg,jpeg,png"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.6.3:8761/eureka

## server url (use send workspace invite mail)
serverUrl: "http://192.168.6.3:8082"

## rediect url (use send workspace invite mail)
redirectUrl: "https://192.168.6.3:8878"

## Feign
feign:
  hystrix:
    enabled: true

