spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://localhost:3306/workspace?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    port: 32768
    database: 0
    host: localhost
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.virnect.workspace.application.*: DEBUG

## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "upload/"
  url: "http://localhost:${server.port}/workspaces/"
  allow-extension: "gif,jpg,jpeg,png"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


## server url (use send workspace invite mail)
serverUrl: "http://localhost:8082"

## client url (use send workspace invite mail)
redirectUrl: "https://localhost:8878"

## Feign
feign:
  hystrix:
    enabled: true


