spring:
  application:
    name: WorkspaceServer
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/smic?serverTimezone=UTC
    username: virnect-smic
    password: virnect1234!
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true


## Server Configuration
server:
  port: 8080
  servlet:
    context-path: "/workspaces"


## Project Configuration
file:
  upload-path: "upload/"
  url: "http://localhost:${server.port}"
  allow-extension: "gif,jpg,jpeg,png"
