spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.6.3:4336/workspace?serverTimezone=UTC
    username: virnect-read
    password: virnect1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: false
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    host: 192.168.6.3
    port: 6379
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
  messages:
    encoding: UTF-8
    basename: classpath:/messages
  zipkin:
    enabled: false
    base-url: http://localhost:9411
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql: debug
    com.virnect.workspace.application.*: DEBUG
## Server Configuration
server:
  port: 8082
  ssl:
    enabled: false
    key-store: virnect.pfx
    key-store-type: PKCS12
    key-store-password: 123456

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

## Mail send redirect Url
redirect:
  workspace-server: "https://localhost:8082"
  workstation-web: "https://192.168.6.3:8878"
  contact-web: "https://192.168.6.3:3000/contact/inquiry"
  account-web: "https://192.168.6.3:8822"
  support-web: "https://192.168.6.3:3000/support"
  signup-web: "https://192.168.6.3:8878/signup"
  members-web: "https://192.168.6.3:8878/members"

## Feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: FULL

hystrix:
  command:
    "LicenseRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "UserRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50
    "MessageRestService":
      execution.isolation.thread.timeoutInMilliseconds: 1000
      metrics.rollingStats.timeInMilliseconds: 60000
      circuitBreaker.requestVolumeThreshold: 5
      circuitBreaker.errorThresholdPercentage: 50

# monitoring
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}

## Minio
minio:
  access-key: "virnect"
  secret-key: "Qjsprxm13@$"
  server: "https://192.168.6.3:2838"
  bucket: "virnect-platform"
  resource: "workspace/profile"
  extension: "gif,jpg,jpeg,png"

user-server:
  ribbon:
    listOfServers: http://192.168.6.3:8081
license-server:
  ribbon:
    listOfServers: http://192.168.6.3:8632