spring:
  application:
    name: platform-server
  config:
    import: "optional:configserver:${CONFIG_SERVER}"
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${VIRNECT_ENV}
  profiles:
    active: ${VIRNECT_ENV}