spring:
  application:
    name: WorkspaceServer
  datasource:
    url: jdbc:mysql://localhost:3306/smic?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
  redis:
    port: 32768
    database: 0
    host: localhost
logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    com.virnect.workspace.application.*: DEBUG


## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "upload/"
  url: "http://localhost:${server.port}"
  allow-extension: "gif,jpg,jpeg,png"

# User Server Configuration
user:
  serverUrl: "http://localhost:8081/users"

# Message Server Configuration
message:
  serverUrl: "http://localhost:8084/messages"

serverUrl: "https://localhost:8082"
