spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://platform-prod-db.cxb5wiohfeko.ap-northeast-2.rds.amazonaws.com:8204/workspaces
    username: virnect-workspaces
    password: qjsprxm2020!#@$
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    host: virnect-prod-redis.b84gc2.0001.apn2.cache.amazonaws.com
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 400MB
  zipkin:
    base-url: http://zipkin.virnect.com

logging:
  level:
    com.virnect.workspace.application.*: DEBUG

## Server Configuration
server:
  port: 8082

## Project Configuration
file:
  upload-path: "workspace/profile/"
  url: "https://virnect-platform.s3.ap-northeast-2.amazonaws.com/"
  allow-extension: "gif,jpg,jpeg,png"

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka.virnect.com/eureka

## AWS Storage
cloud:
  aws:
    credentials:
      access-key: AKIARQGLJD3UCFBXNUWQ
      secret-key: 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
    region:
      auto: true
    s3:
      bucket:
        name: "virnect-platform"
        resource: "workspace/profile"

## Mail send rediect Url
serverUrl: "https://api.virnect.com"
redirectUrl: "https://workstation.virnect.com"
contactUrl: "https://virnect.com/contact/inquiry"
accountUrl: "https://account.virnect.com"
supportUrl: "https://virnect.com/contact/inquiry"

## Feign
feign:
  hystrix:
    enabled: true
