spring:
  application:
    name: workspace-server
  datasource:
    url: jdbc:mysql://192.168.0.211:4336/workspace?serverTimezone=UTC
    username: virnect-workspace
    password: virnect1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
  redis:
    host: 192.168.0.211
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 40MB
  zipkin:
    base-url: http://192.168.0.211:9411
    discovery-client-enabled: false
    enabled: false

logging:
  level:
    com.virnect.platform.workspace.application.*: INFO

## Server Configuration
server:
  port: 8082

## Eureka Server Configuration
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.212.134.102
  client:
    service-url:
      defaultZone: http://192.168.0.211:8761/eureka
    registry-fetch-interval-seconds: 3
    enabled: false


## Mail send rediect Url
redirect:
  workspace-server: "http://192.168.0.211:8082"
  workstation-web: "https://192.168.0.211:8878"
  contact-web: "https://192.168.0.211:3000/contact/inquiry"
  account-web: "https://192.168.0.211:8822"
  support-web: "https://www.virnect.com/support/inquiry"
  terms-web: "https://192.168.0.211:8883/terms"
  members-web: "https://192.168.0.211:8878/members"
  console-web: "https://192.168.0.211:8883"

## Feign
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        loggerLevel: FULL
  httpClient:
    disableSslValidation: true
    enabled: false
  okhttp:
    enabled: true


# monitoring
management:
  endpoints:
    enabled-by-default: false

## Minio
minio:
  access-key: "virnect"
  secret-key: "Qjsprxm13@$"
  server: "https://192.168.0.211:2838"
  bucket: "virnect-platform"
  extension: "gif,jpg,jpeg,png"


workspace-server:
  ribbon:
    listOfServers: http://192.168.0.211:8082
license-server:
  ribbon:
    listOfServers: http://localhost:8632
message-server:
  ribbon:
    listOfServers: http://192.168.0.211:8084
remote-service-server:
  ribbon:
    listOfServers: http://192.168.0.211:8000
account-server:
  ribbon:
    listOfServers: http://192.168.0.211:8322


ribbon:
  eureka:
    enabled: false


decorator:
  datasource:
    p6spy:
      enable-logging: true